name: CI

# Controls when the action will run.

on: 
  #triggers the workflow on push or pull-reuest events but only for the mater branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  #Alllow you to run this workflow manually from the action  tab
  workflow_dispatch:

# A workflow run is madeup of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The Type of runner that the job will run on
    runs-on: ubuntu-latest

    #steps represent a sequence of tasls wthat willbe executed as a part of the job.
    steps:
      #check-out your repo under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      #Runs a single command using the runner shell
      - name: Runa a on-line script
        run: echo Hello, World!

      #Runs a set of command using the runner shell
      - name: run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
